<?php 

/**
 * Implements hook_permission().
 */
function dcww_js_node_permission() {
  return array(
    'access cornify' => array(
      'title' => t('Access cornify'),
    ),
    'i say so' => array(
      'title' => t('Only if I say so'),
    ),
  );
}

/**
* Implements hook_preprocess_node().
*/
function dcww_js_node_preprocess_node(&$vars) {

  //print_r($vars);

  if ($vars["type"] == "article") { 
    if (user_access("access cornify") && user_access("i say so")) {

	drupal_add_js(drupal_get_path("module","dcww_js")."/cornify/cornify.js");
	drupal_add_js(drupal_get_path("module","dcww_js")."/cornify/cornifykeys.js");

    }
	
  }

}
